In [5]:
import requests
import pandas as pd

In [6]:
URL = "https://stephen-king-api.onrender.com/api/books"

response = URL
response = requests.get(URL)

In [9]:
json_data = response.json()
df = pd.json_normalize(json_data["data"])
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [10]:
# cleaning data on id basis

df = df[['id','Title','Year','ISBN']]
df

    id            Title  Year                  ISBN
0    1           Carrie  1974     978-0-385-08695-0
1    2      Salem's Lot  1975     978-0-385-00751-1
2    3      The Shining  1977     978-0-385-12167-5
3    4             Rage  1977     978-0-451-07645-8
4    5        The Stand  1978     978-0-385-12168-2
..  ..              ...   ...                   ...
59  60        Elevation  2018     978-1-98210-231-9
60  61    The Institute  2019     978-1-98211-056-7
61  62            Later  2021     978-1-78909-649-1
62  63    Billy Summers  2021     978-1-982-17361-6
63  72  The Roopak Zone  1979  978-0-670-26069697-5

[64 rows x 4 columns]

data cleaning

In [11]:
import requests
import pandas as pd

In [14]:
URL = "https://dogapi.dog/api/v2/breeds"

res = URL
res = requests.get(URL)
json_data = res.json()

#Now pandas
df = pd.json_normalize(json_data["data"])
df = df[['attributes.name','type','attributes.male_weight.max','attributes.traits.apartment_friendly']]
df = df.sort_values("attributes.traits.apartment_friendly", ascending = False)
df = df.reset_index(drop = True)
df = df.fillna(0)
df

,attributes.name,type,attributes.male_weight.max,attributes.traits.apartment_friendly
0,Affenpinscher,breed,6,5.0
1,Basset Hound,breed,29,4.0
2,American Hairless Terrier,breed,6,4.0
3,Australian Terrier,breed,7,4.0
4,Beagle,breed,14,3.0
5,Alaskan Klee Kai,breed,10,3.0
6,Basenji,breed,11,3.0
7,American Eskimo Dog,breed,20,3.0
8,American Staffordshire Terrier,breed,40,3.0
9,Australian Cattle Dog,breed,23,2.0
10,Basset Fauve de Bretagne,breed,19,2.0
11,Barbet,breed,27,2.0
12,Barbado da Terceira,breed,30,2.0
13,Azawakh,breed,25,2.0
14,Australian Stumpy Tail Cattle Dog,breed,20,2.0
15,Australian Shepherd,breed,30,2.0
16,Bearded Collie,breed,25,2.0
17,Afghan Hound,breed,27,2.0
18,American Water Spaniel,breed,20,2.0
19,American Bulldog,breed,50,2.0
20,Akita,breed,60,2.0
21,Airedale Terrier,breed,23,2.0
22,Australian Kelpie,breed,20,1.0
23,Appenzeller Sennenhund,breed,32,1.0
24,American Leopard Hound,breed,34,1.0
25,American Foxhound,breed,32,1.0
26,American English Coonhound,breed,29,1.0
27,Alaskan Malamute,breed,39,1.0
28,Anatolian Shepherd Dog,breed,70,1.0
29,Bavarian Mountain Scent Hound,breed,30,0.0

In [15]:
# save this file

df.to_csv("cleaned_dog_data.csv", index=False)
print("CSV file created successfully!")

CSV file created successfully!